export const HOME_SCREEN = "HOME_SCREEN";
export const LOCATION1_SCREEN = "LOCATION1_SCREEN";
export const LOCATION2_SCREEN = "LOCATION2_SCREEN";
export const LOCATION3_SCREEN = "LOCATION3_SCREEN";
export const LOCATION4_SCREEN = "LOCATION4_SCREEN";
export const LOCATION5_SCREEN = "LOCATION5_SCREEN";
export const LOCATION6_SCREEN = "LOCATION6_SCREEN";
export const CAMERA_SCREEN = "CAMERA_SCREEN";
